CREATE OR REPLACE TRIGGER UPDATE_PART_INVENTORY_INCOMING
    AFTER INSERT 
        ON PURCHASE_ORDER
        FOR EACH ROW
    DECLARE
        ID_PART PART.PART_ID%TYPE;
        AP_ID PURCHASE_ORDER.PART_APPR_ID%TYPE;
    BEGIN
        AP_ID := :NEW.PART_APPR_ID;
        SELECT PART_ID INTO ID_PART FROM APPROVAL_DETAILS WHERE PART_APPR_ID = AP_ID;
        UPDATE PART P 
            SET P.INVENTORY = NVL(P.INVENTORY,0) + :NEW.ITEM_QTY
        WHERE 
            P.PART_ID = ID_PART;
    END;
/


CREATE OR REPLACE TRIGGER VERIFY_PART_APPROVAL
    BEFORE INSERT 
        ON PURCHASE_ORDER
        FOR EACH ROW
    DECLARE
--        ID_PART PART.PART_ID%TYPE;
        AP_STATUS APPROVAL_DETAILS.APP_STATUS%TYPE;
        AP_ID PURCHASE_ORDER.PART_APPR_ID%TYPE;
    BEGIN
        AP_ID := :NEW.PART_APPR_ID;
        SELECT APP_STATUS INTO AP_STATUS FROM APPROVAL_DETAILS WHERE PART_APPR_ID = AP_ID;
        IF AP_STATUS != 'APPROVED' 
        THEN
            RAISE_APPLICATION_ERROR(-20001, 'ITEM NOT APPROVED FOR PURCHASE');    
        END IF;
    END
;
/