--customer user

CREATE USER SCDB_CUST IDENTIFIED BY custpassword;
GRANT CONNECT TO SCDB_CUST;
GRANT SELECT ON SCDB.CUSTOMER TO SCDB_CUST;
GRANT SELECT ON SCDB.PROJECT_BY_CUSTOMER TO SCDB_CUST;
GRANT SELECT ON SCDB.CUSTOMER_PROGRAM_EMPLOYEE TO SCDB_CUST;
GRANT SELECT ON SCDB.CUSTOMER_PROGRAM_PART TO SCDB_CUST;    
GRANT SELECT ON SCDB.CUSTOMER_PROGRAM_INVOICE TO SCDB_CUST;


CREATE USER SCDB_SUPP IDENTIFIED BY suppassword;
GRANT CONNECT TO SCDB_SUPP;
GRANT SELECT ON SCDB.SUPPLIER TO SCDB_SUPP;
GRANT SELECT, INSERT, UPDATE ON SCDB.SUPPLIER_CONTACT TO SCDB_SUPP;
GRANT SELECT ON SCDB.APPROVAL_DETAILS TO SCDB_SUPP;
GRANT SELECT ON SCDB.PART_APPROVAL_SUPPLIER TO SCDB_SUPP;

CREATE USER SCDB_EMP IDENTIFIED BY emppassword;
GRANT CONNECT TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.CUSTOMER TO SCDB_EMP;
GRANT SELECT ON SCDB.EMPLOYEE TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.PART TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.PROGRAMS TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.EMPLOYEE_PROGRAM TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.PROGRAM_PART TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.OUTGOING_INVOICE TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.APPROVAL_DETAILS TO SCDB_EMP; 
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.PURCHASE_ORDER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.SUPPLIER_CONTACT TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.SUPPLIER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.PROJECT_BY_CUSTOMER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.APPROVAL_WITH_EMPLOYEE TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.APPROVAL_WITH_SUPPLIER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.EVALUATION_STATS_SUPPLIER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.PART_APPROVAL_SUPPLIER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.ACTIVE_SUPPLIER TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.INVENTORY_FLOW_STATUS TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.CUSTOMER_PROGRAM_EMPLOYEE TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.CUSTOMER_PROGRAM_PART TO SCDB_EMP;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.CUSTOMER_PROGRAM_INVOICE TO SCDB_EMP;

CREATE USER SCDB_HR IDENTIFIED BY hrpassword;
GRANT CONNECT TO SCDB_HR;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.EMPLOYEE TO SCDB_HR;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCDB.EVALUATION_STATS_EMPLOYEE TO SCDB_HR;

CREATE USER SCDB_MANAGER IDENTIFIED BY managerpassword;
GRANT ALL PRIVILEGES TO SCDB_MANAGER;


