--SELECT * FROM PROGRAMS;
--SELECT * FROM CUSTOMER;

--VIEW PROJECT_BY_CUSTOMER
CREATE VIEW PROJECT_BY_CUSTOMER AS SELECT C.CUST_ID AS CUSTOMER_ID, C.CUST_NAME AS CUSTOMER_NAME, P.PROG_NAME AS PROGRAM_NAME,P.PROG_ID PROGRAM_ID, P.PROG_START PROGRAM_START, P.PROG_END PROGRAM_END,P.PROG_STATUS PROGRAM_STATUS FROM CUSTOMER C LEFT OUTER JOIN PROGRAMS P
   ON C.CUST_ID = P.CUST_ID; 
   
SELECT * FROM project_by_customer;

-- FIND CUSTOMER WHO NEVER STARTED A PROGRAM
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME  FROM PROJECT_BY_CUSTOMER WHERE PROGRAM_ID IS NULL;

--FIND CUSTOMER WITH NO ACTIVE PROJECT
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME , ROUND(MONTHS_BETWEEN(SYSDATE,PROGRAM_END)/12) AS INACTIVE_SINCE_YEARS 
    FROM PROJECT_BY_CUSTOMER 
    WHERE EXTRACT(YEAR FROM PROGRAM_END) < EXTRACT(YEAR FROM (SYSDATE));

