--SELECT * FROM PROGRAMS;
--SELECT * FROM CUSTOMER;

--VIEW PROJECT_BY_CUSTOMER
CREATE VIEW PROJECT_BY_CUSTOMER AS SELECT C.CUST_ID AS CUSTOMER_ID, C.CUST_NAME AS CUSTOMER_NAME, P.PROG_NAME AS PROGRAM_NAME,P.PROG_ID PROGRAM_ID, P.PROG_START PROGRAM_START, P.PROG_END PROGRAM_END,P.PROG_STATUS PROGRAM_STATUS FROM CUSTOMER C LEFT OUTER JOIN PROGRAMS P
   ON C.CUST_ID = P.CUST_ID; 

SELECT * FROM PROJECT_BY_CUSTOMER;

-- FIND CUSTOMER WHO NEVER STARTED A PROGRAM
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME  FROM PROJECT_BY_CUSTOMER WHERE PROGRAM_ID IS NULL;

--FIND CUSTOMER WITH NO ACTIVE PROJECT
SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME , ROUND(MONTHS_BETWEEN(SYSDATE,PROGRAM_END)/12) AS INACTIVE_SINCE_YEARS 
    FROM PROJECT_BY_CUSTOMER 
    WHERE EXTRACT(YEAR FROM PROGRAM_END) < EXTRACT(YEAR FROM (SYSDATE))
    OR 
    PROGRAM_END IS NULL
    ORDER BY ROUND(MONTHS_BETWEEN(SYSDATE,PROGRAM_END)/12) DESC NULLS LAST;


--COUNT NUMBER OF PROJECTS PER CUSTOMER

SELECT CUSTOMER_ID, CUSTOMER_NAME,NVL(COUNT(*),0)  
    FROM PROJECT_BY_CUSTOMER
    WHERE PROGRAM_ID IS NOT NULL
    GROUP BY customer_id, CUSTOMER_NAME
    ORDER BY COUNT(*) DESC;
    
    
SELECT * FROM approval_details;
SELECT * FROM program_part;
SELECT * FROM PART;
SELECT * FROM EMPLOYEE;

CREATE VIEW APPROVAL_WITH_EMPLOYEE AS
SELECT A.PART_APPR_ID AS APPROVAL_ID, A.PART_ID AS PART_ID, A.SUPP_ID, A.APP_STATUS AS STATUS, A.APP_DATE AS STATUS_DATE, A.APP_COST AS COST,
E.EMP_ID AS APP_EMP_ID, E.EMP_NAME AS EMP_NAME FROM APPROVAL_DETAILS A LEFT OUTER JOIN EMPLOYEE E ON A.SQE_REP = E.EMP_ID;

SELECT * FROM APPROVAL_WITH_EMPLOYEE;

--SELECT EMPLOYEE WITH MAXIMUM PRODUCT EVALUATIONS
SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS EVALUATIONS FROM APPROVAL_WITH_EMPLOYEE 
WHERE STATUS != 'PENDING'
GROUP BY APP_EMP_ID, EMP_NAME
ORDER BY COUNT(*) DESC;

SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS APPROVED FROM APPROVAL_WITH_EMPLOYEE
WHERE STATUS = 'APPROVED'
GROUP BY APP_EMP_ID, EMP_NAME;

SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS DENIED FROM APPROVAL_WITH_EMPLOYEE
WHERE STATUS = 'DENIED'
GROUP BY APP_EMP_ID, EMP_NAME;

SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS PENDING FROM APPROVAL_WITH_EMPLOYEE
WHERE STATUS = 'PENDING'
GROUP BY APP_EMP_ID, EMP_NAME;

--SELECT APPROVAL STATS BY EMPLOYEE
SELECT DISTINCT A.APP_EMP_ID, A.EMP_NAME , NVL(X.APPROVED,0) AS APPROVED, NVL(D.DENIED,0) AS DENIED, NVL(P.PENDING,0) AS PENDING 
FROM APPROVAL_WITH_EMPLOYEE A 
    LEFT JOIN (
        SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS APPROVED FROM APPROVAL_WITH_EMPLOYEE
            WHERE STATUS = 'APPROVED'
            GROUP BY APP_EMP_ID, EMP_NAME
        ) X ON A.APP_EMP_ID = X.APP_EMP_ID
    LEFT JOIN(
        SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS DENIED FROM APPROVAL_WITH_EMPLOYEE
            WHERE STATUS = 'DENIED'
            GROUP BY APP_EMP_ID, EMP_NAME
    ) D ON A.APP_EMP_ID = X.APP_EMP_ID
    LEFT JOIN(
        SELECT APP_EMP_ID, EMP_NAME, COUNT(*) AS PENDING FROM APPROVAL_WITH_EMPLOYEE
            WHERE STATUS = 'PENDING'
            GROUP BY APP_EMP_ID, EMP_NAME
    ) P ON A.APP_EMP_ID = P.APP_EMP_ID;
----------------------------------

CREATE VIEW APPROVAL_WITH_SUPPLIER AS
SELECT A.PART_APPR_ID AS APPROVAL_ID, A.PART_ID AS PART_ID, A.SUPP_ID AS SUPPLIER_ID, S.SUPP_NAME AS SUPPLIER_NAME, A.APP_STATUS AS STATUS, A.APP_DATE AS STATUS_DATE 
FROM APPROVAL_DETAILS A LEFT OUTER JOIN SUPPLIER S ON A.SUPP_ID = S.SUPP_ID;

--SELECT * FROM APPROVAL_WITH_SUPPLIER;

SELECT SUPPLIER_ID, COUNT(*) AS APPROVED FROM APPROVAL_WITH_SUPPLIER
WHERE STATUS = 'APPROVED'
GROUP BY SUPPLIER_ID;

SELECT SUPPLIER_ID, COUNT(*) AS PENDING FROM APPROVAL_WITH_SUPPLIER
WHERE STATUS = 'PENDING'
GROUP BY SUPPLIER_ID;

SELECT SUPPLIER_ID, COUNT(*) AS DENIED FROM APPROVAL_WITH_SUPPLIER
WHERE STATUS = 'DENIED'
GROUP BY SUPPLIER_ID;

SELECT DISTINCT S.SUPPLIER_ID, S.SUPPLIER_NAME , NVL(A.APPROVED,0) AS APPROVED, NVL(D.DENIED,0) AS DENIED ,NVL(P.PENDING,0) AS PENDING FROM APPROVAL_WITH_SUPPLIER S 
    LEFT JOIN(
        SELECT SUPPLIER_ID, COUNT(*) AS APPROVED FROM APPROVAL_WITH_SUPPLIER
            WHERE STATUS = 'APPROVED'
            GROUP BY SUPPLIER_ID
    ) A ON S.SUPPLIER_ID = A.SUPPLIER_ID
    LEFT JOIN(
        SELECT SUPPLIER_ID, COUNT(*) AS DENIED FROM APPROVAL_WITH_SUPPLIER
            WHERE STATUS = 'DENIED'
            GROUP BY SUPPLIER_ID
    ) D ON S.SUPPLIER_ID = D.SUPPLIER_ID
    LEFT JOIN(
        SELECT SUPPLIER_ID, COUNT(*) AS PENDING FROM APPROVAL_WITH_SUPPLIER
            WHERE STATUS = 'PENDING'
            GROUP BY SUPPLIER_ID
    ) P ON S.SUPPLIER_ID = P.SUPPLIER_ID 
    ;
