--INSERT DATA INTO 'CUSTOMER'
INSERT INTO SCDB.CUSTOMER
    (CUST_ID, CUST_NAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_REGION)
    VALUES
    (CUST_ID_SEQ.NEXTVAL, '&CUST_NAME', '&CUST_STREET', '&CUST_CITY', '&CUST_STATE', '&CUST_ZIP', '&CUST_REGION');

SELECT * FROM CUSTOMER;


--INSERT TEST DATA INTO 'EMPLOYEE'
INSERT INTO SCDB.EMPLOYEE 
    (EMP_ID, EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE) 
    VALUES 
    (EMP_ID_SEQ.NEXTVAL, '&EMP_NAME','&EMP_DOB','&EMP_STREET','&EMP_CITY','&EMP_STATE','&EMP_ZIP','&EMP_HIREDATE');

SELECT * FROM EMPLOYEE;


--INSERT DATA INTO 'PART'
INSERT INTO SCDB.PART
    (PART_ID, PART_NAME, COMMODITY, STATUS, QTY_UNIT) 
    VALUES 
    (PART_NUM_SEQ.NEXTVAL, '&PART_NAME', '&COMMODITY', '&PART_STATUS', &QTY_UNIT);  

SELECT * FROM PART;


--INSERT DATA INTO 'SUPPLIER'
INSERT INTO SCDB.SUPPLIER 
    (SUPP_ID, SUPP_NAME, SUPP_STREET, SUPP_CITY, SUPP_STATE, SUPP_ZIP, SUPP_REGION) 
    VALUES 
    (SUPP_ID_SEQ.NEXTVAL, '&SUPP_NAME', '&SUPP_STREET', '&SUPP_CITY', '&SUPP_STATE', '&SUPP_ZIP', '&SUPP_REGION');   

SELECT * FROM SUPPLIER;



--INSERT DATA INTO SUPPLIER_CONTACT
INSERT INTO SCDB.SUPPLIER_CONTACT 
    (SUPP_EMP_ID, SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    (SUPP_EMPID_SEQ.NEXTVAL, '&SUPP_EMP_NAME', '&SUPP_EMP_EMAIL', '&SUPP_EMP_PHONE', '&SUPP_EMP_DESIGNATION', '&SUPP_EMP_START', '&SUPP_EMP_END', '&SUPP_ID');

SELECT * FROM SUPPLIER_CONTACT;



--INSERT DATA INTO 'PROGRAMS'
INSERT INTO SCDB.PROGRAMS
    (PROG_ID, PROG_NAME, PROG_START, PROG_END, AVG_PROD_WEEKLY, MAX_PROD_WEEKLY, PROG_STATUS, CUST_ID) 
    VALUES 
    (PROG_ID_SEQ.NEXTVAL, '&PROG_NAME', '&PROG_START', '&PROG_END', &PROG_APW, &PROG_MPW, '&PROG_STATUS', '&CUST_ID');

SELECT * FROM PROGRAMS;


--INSERT DATA INTO 'PROGRAM_PART'
INSERT INTO SCDB.PROGRAM_PART
    (PROG_PART_ID, PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (PROG_PART_ID_SEQ.NEXTVAL, &PROG_ID, &PART_ID, &QTY_FACTOR);
--SELECT * FROM PROGRAM_PART;



--INSERT TEST DATA INTO 'EMPLOYEE_PROGRAM'
INSERT INTO SCDB.EMPLOYEE_PROGRAM
    (EMP_PROG_ID, EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (EMP_PROG_ID_SEQ.NEXTVAL, &EMP_ID, &PROG_ID, '&DESIGNATION', '&START_DATE', '&END_DATE');
SELECT * FROM EMPLOYEE_PROGRAM;



--INSERT TEST DATA INTO 'APPROVAL_DETAILS'
INSERT INTO APPROVAL_DETAILS
    (PART_APPR_ID, PART_ID, SUPP_ID, APP_STATUS, SUBMIT_DATE, APP_DATE, SQE_REP, APP_COST, AVG_PROD_WEEKLY, MAX_PROD_WEEKLY)
    VALUES
    (PART_APP_ID_SEQ.NEXTVAL, &PART_ID, &SUPP_ID, '&APP_STATUS','&SUBMIT_DATE', '&APP_DATE', &SQE_REP, &APP_COST, &AVG_PROD_WEEKLY, &MAX_PROD_WEEKLY);

SELECT * FROM APPROVAL_DETAILS;



--INSERT TEST DATA INTO 'PURCHASE_ORDER'
INSERT INTO PURCHASE_ORDER
    (PO_NO, PART_APPR_ID, PO_DATE, ITEM_QTY)
    VALUES
    (PO_NO_SEQ.NEXTVAL, &PART_APPR_ID, '&PO_DATE', &ITEM_QTY);
--SELECT * FROM PURCHASE_ORDER;




--INSERT TEST DATA INTO 'OUTGOING_INVOICE'
INSERT INTO OUTGOING_INVOICE
    (OUT_INV_NO, OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    (OUT_INV_NO_SEQ.NEXTVAL, '&OUT_INV_DATE', &QUANTITY, '&QTY_UNIT', &COST_PER_UNIT, '&COST_UNIT', &PROG_PART_ID); 
--SELECT * FROM OUTGOING_INVOICE;