--SELECT ALL CUSTOMER
SELECT * FROM SCDB.CUSTOMER C;
--SELECT CUSTOMER FROM A REGION
SELECT * FROM SCDB.CUSTOMER C WHERE C.CUST_REGION = '&REGION';


--SELECT ALL PROGRAMS
SELECT * FROM SCDB.PROGRAMS;
--SELECT ACTIVE PROGRAM
SELECT * FROM SCDB.PROGRAMS WHERE PROG_STATUS IN ('OPEN', 'DELAYED');
--SEE PROGRAM BY STATUS
Select * FROM SCDB.PROGRAMS WHERE PROG_STATUS = '&PROGRAM_STATUS'; 
--SEE PROGRAM BY YEAR AND PROGRAM_STATUS
Select * FROM SCDB.PROGRAMS P WHERE &YEAR BETWEEN EXTRACT(YEAR FROM P.PROG_START) AND EXTRACT(YEAR FROM P.PROG_END);
--SECLECT PROGRAM BY STATS AND YEAR
Select * FROM SCDB.PROGRAMS P WHERE &YEAR BETWEEN EXTRACT(YEAR FROM P.PROG_START) AND EXTRACT(YEAR FROM P.PROG_END)
    AND PROG_STATUS = '&PROGRAM_STATUS';


--SELECT ALL EMPLOYEE
SELECT * FROM SCDB.EMPLOYEE;
--SELECT ACTIVE EMPLOYEE
SELECT * FROM SCDB.EMPLOYEE WHERE EMP_ENDDATE IS NULL AND EMP_HIREDATE <= TRUNC(SYSDATE);
--SELECT NOT ACTIVE EMPLOYEE
SELECT * FROM SCDB.EMPLOYEE WHERE EMP_ENDDATE IS NOT NULL;
--SELECT EMPLOYEE BY YEAR
SELECT * FROM SCDB.EMPLOYEE E WHERE '&YEAR' BETWEEN EXTRACT(YEAR FROM E.EMP_HIREDATE) AND EXTRACT(YEAR FROM E.EMP_HIREDATE);


--SELECT ALL PARTS
SELECT * FROM SCDB.PART;
--SELECT PARTS BY COMMODITY
SELECT * FROM SCDB.PART WHERE COMMODITY = '&COMMODITY';
--SELECT PART BY PART STATUS
SELECT * FROM SCDB.PART WHERE STATUS = 'OPEN'; 
SELECT * FROM SCDB.PART WHERE STATUS = 'CLOSED'; 
--SELECT PART BY COMMODITY AND STATUS 
SELECT * FROM SCDB.PART WHERE COMMODITY = '&COMMODITY' AND STATUS = 'OPEN';
SELECT * FROM SCDB.PART WHERE COMMODITY = '&COMMODITY' AND STATUS = 'CLOSED';


--SELECT ALL SUPPLIER
SELECT * FROM SCDB.SUPPLIER;
--SELECT SUPPLIER FROM REGION
SELECT * FROM SCDB.SUPPLIER WHERE SUPP_REGION = '&REGION';


--SELECT ALL SUPPLIER CONTACT
SELECT * FROM SCDB.SUPPLIER_CONTACT;