--SELECT ALL CUSTOMER
SELECT * FROM SCDB.CUSTOMER C;

--SELECT CUSTOMER FROM A REGION
SELECT * FROM SCDB.CUSTOMER C WHERE C.CUST_REGION = '&REGION';

--SELECT ALL PROGRAMS
SELECT * FROM SCDB.PROGRAMS;

--SELECT ACTIVE PROGRAM
SELECT * FROM SCDB.PROGRAMS WHERE PROG_STATUS IN ('OPEN', 'DELAYED');

--SEE PROGRAM BY STATUS
Select * FROM SCDB.PROGRAMS WHERE PROG_STATUS = '&PROGRAM_STATUS'; 

--SEE PROGRAM BY YEAR AND PROGRAM_STATUS
Select * FROM SCDB.PROGRAMS P WHERE &YEAR BETWEEN EXTRACT(YEAR FROM P.PROG_START) AND EXTRACT(YEAR FROM P.PROG_END);
Select * FROM SCDB.PROGRAMS P WHERE &YEAR BETWEEN EXTRACT(YEAR FROM P.PROG_START) AND EXTRACT(YEAR FROM P.PROG_END)
    AND PROG_STATUS = '&PROGRAM_STATUS';

--SELECT ALL EMPLOYEE
SELECT * FROM EMPLOYEE;

--SELECT ACTIVE EMPLOYEE
SELECT * FROM EMPLOYEE WHERE EMP_ENDDATE IS NULL;

--SELECT NOT ACTIVE EMPLOYEE
SELECT * FROM EMPLOYEE WHERE EMP_ENDDATE IS NOT NULL;

------------------------------------------------------------DONE TILL HERE-----------------------------------------

--SELECT EMPLOYEE BY YEAR
SELECT * FROM 