--INSERT TEST DATA INTO 'CUSTOMER'

INSERT INTO CUSTOMER
(CUST_NAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_REGION)
VALUES
('CONVETRY PIPINGS', '929 KENNEDY EXPRESS', 'LONG BEACH', 'CALIFORNIA', '90774', 'W');

INSERT INTO CUSTOMER
(CUST_NAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_REGION)
VALUES
('WELLPOINT PLASTICS', '289 FRANCIS', 'GRAND RAPIDS', 'MICHIGAN', '49510', 'N');

INSERT INTO CUSTOMER
(CUST_NAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_REGION)
VALUES
('BIOMET GROUP', '277 TOOKER', 'SPRINGFIELDS', 'MASSACHUSETTS', '01179', 'NE');

INSERT INTO CUSTOMER
(CUST_NAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_REGION)
VALUES
('CARMAX CORPORATIONS', '120 WASHINGTON STREET', 'MORENO', 'CALIFORNIA', '92508', 'W');

INSERT INTO CUSTOMER
(CUST_NAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_REGION)
VALUES
('ROCHESTER BEARINGS', '1130 PETERSON', 'SYRACUSE', 'NEW YORK', '13208', 'N');

--SELECT * FROM CUSTOMER;




--INSERT TEST DATA INTO 'EMPLOYEE'

INSERT INTO EMPLOYEE 
    (EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE) 
    VALUES 
    ('MADELEINE REYES','01-APR-1979','9020 BESSIE COLEMAN','NEW HAVEN','CONNECTICUT','06556','15-JAN-2007');

INSERT INTO EMPLOYEE 
    (EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE) 
    VALUES 
    ('AMYA KINNEY','16-MAR-1981','PINE STREET','Cambridge','MA','02214','04-SEP-2009');
    
INSERT INTO EMPLOYEE 
    (EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE) 
    VALUES 
    ('CATLYN PETERS','13-OCT-1991','742 ORNAGO AVENUE','LEXINTON','MA','02223','02-JUL-2011');
    
INSERT INTO EMPLOYEE 
    (EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE) 
    VALUES 
    ('MORIAH NASH','25-AUG-1992','SIMMONS STREET','WARREN','MICHIGAN','48033','05-FEB-2015');
    
INSERT INTO EMPLOYEE 
    (EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE) 
    VALUES 
    ('PATRICK HANSEN','25-SEP-1985','485 PEASANT STREET','COLORADO SPRINGS','SPRINGS','80772','05-AUG-2010');
    
INSERT INTO EMPLOYEE 
    (EMP_NAME, EMP_DOB, EMP_STREET, EMP_CITY, EMP_STATE, EMP_ZIP, EMP_HIREDATE, EMP_ENDDATE) 
    VALUES 
    ('SHANK BARTON','14-MAY-1982','614 SHAWMUT AVENUE','BOSTON','MA','02118','14-FEB-1998', '03-MAY-2016');


--SELECT * FROM EMPLOYEE;


--INSERT TEST DATA INTO 'PART'

INSERT INTO PART(PART_NAME, COMMODITY, STATUS, QTY_UNIT) VALUES ('BEARING', 'FORGING', 'OPEN', 'PIECE');
INSERT INTO PART(PART_NAME, COMMODITY, STATUS, QTY_UNIT) VALUES ('ROLLER', 'FORGING', 'OPEN', 'PIECE');
INSERT INTO PART (PART_NAME, COMMODITY, STATUS, QTY_UNIT) VALUES ('SPARK ELECTRODE', 'POWDER METALLURGY', 'OPEN', 'POUNDS'); 
INSERT INTO PART (PART_NAME, COMMODITY, STATUS, QTY_UNIT) VALUES ('PACKAGING ROD', 'PLASTIC', 'OPEN', 'PIECE'); 
INSERT INTO PART (PART_NAME, COMMODITY, STATUS, QTY_UNIT) VALUES ('VIBRATOR', 'SCREW MACHINE', 'OPEN', 'PIECE');
INSERT INTO PART (PART_NAME, COMMODITY, STATUS, QTY_UNIT) VALUES ('PISTON VALVES', 'POWDER METALLURGY', 'OPEN', 'POUNDS');

--SELECT * FROM PART;


--INSERT TEST DATA INTO 'SUPPLIER'

INSERT INTO SUPPLIER 
    (SUPP_NAME, SUPP_STREET, SUPP_CITY, SUPP_STATE, SUPP_ZIP, SUPP_REGION) 
    VALUES 
    ('OSHKASH CORPORATION', '8004 TAFT', 'HUNTSVILLA', 'ALABAMA', '35808', 'SE');
    
INSERT INTO SUPPLIER 
    (SUPP_NAME, SUPP_STREET, SUPP_CITY, SUPP_STATE, SUPP_ZIP, SUPP_REGION) 
    VALUES 
    ('O REILY AUTOMOTIVE', '201 HOYNE', 'YONKERS', 'NEW YORK', '10776', 'NE');
    
INSERT INTO SUPPLIER 
    (SUPP_NAME, SUPP_STREET, SUPP_CITY, SUPP_STATE, SUPP_ZIP, SUPP_REGION) 
    VALUES 
    ('BERKSHIRE MANUFACTURERES', '390 HEATH', 'COLUMBIA', 'SOUTH CAROLINA', '29012', 'E');
    
INSERT INTO SUPPLIER 
    (SUPP_NAME, SUPP_STREET, SUPP_CITY, SUPP_STATE, SUPP_ZIP, SUPP_REGION) 
    VALUES 
    ('HELMERICH PLASTICS', '156 STEVENSON DAN RYAN', 'DAYTON', 'OHIO', '45379', 'N');
    
INSERT INTO SUPPLIER 
    (SUPP_NAME, SUPP_STREET, SUPP_CITY, SUPP_STATE, SUPP_ZIP, SUPP_REGION) 
    VALUES 
    ('DST SYSTEMS', '2671 SAYRE', 'BOSTON', 'MASSACHUSETTS', '02746', 'NE');
    
--SELECT * FROM SUPPLIER;


--INSERT INTO SUPPLIER_CONTACT
INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('AUBREE KEITH', 'Aubree.KEITH3@gmail.com', '2516107927', 'KEY ACCOUNTS MANAGER', '25-SEP-2013', NULL, 302);
    
INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('SOLAN HOLDEN', 'SLO.HOLDEN@gmail.com', '6052359572', 'KEY ACCOUNTS MANAGER', '04-APR-1989', '31-JAN-2011', 302);
    
INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('CAILYN SPENCE', 'CAI.SPE65@hushmail.com', '5738974691', 'SALES REPRESENTATIVE', '06-JUL-2014', NULL, 304);
    
INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('ROBERT SEARS', 'ROB.SE60@yahoo.com', '6075130064', 'SENIOR BUYER', '24-JUL-2000', NULL, 305);

INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('MIAH GREER', 'mi.gre8073@live.com', '8483891048', 'COMMODITY MANAGER', '13-MAR-2002', NULL, 301);

INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('SAM HARRIS', 'sam.harris@live.com', '8483696073', 'SALES REPRESENTATIVE', '21-JUL-2005', '03-OCT-2015', 303);

INSERT INTO SUPPLIER_CONTACT 
    (SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE, SUPP_EMP_DESIGNATION, SUPP_EMP_START, SUPP_EMP_END, SUPP_ID) 
    VALUES 
    ('SHINY FULERTON', 's.fulerton@live.com', '8487895600', 'SALES REPRESENTATIVE', '13-FEB-2012', NULL, 303);
  
--SELECT * FROM SUPPLIER_CONTACT;



--INSERT TEST DATA INTO 'PROGRAMS'

INSERT INTO PROGRAMS
    (PROG_NAME, PROG_START, PROG_END, PROG_STATUS, CUST_ID) 
    VALUES 
    ('CATERPILLAR', '03-JAN-2014', '02-JAN-2019', 'DELAYED', '10001');
    
INSERT INTO PROGRAMS
    (PROG_NAME, PROG_START, PROG_END, PROG_STATUS, CUST_ID) 
    VALUES 
    ('STARDUST', '01-JUL-2017', '30-JUN-2022', 'OPEN', '10001');
 
INSERT INTO PROGRAMS
    (PROG_NAME, PROG_START, PROG_END, PROG_STATUS, CUST_ID) 
    VALUES 
    ('SIGNPLUS', '27-FEB-2012', '26-FEB-2017', 'CLOSED', '10003');
    
INSERT INTO PROGRAMS
    (PROG_NAME, PROG_START, PROG_END, PROG_STATUS, CUST_ID) 
    VALUES 
    ('P1ORANGE', '11-MAR-2011', '10-MAR-2016', 'CLOSED', '10004');
    
INSERT INTO PROGRAMS
    (PROG_NAME, PROG_START, PROG_END, PROG_STATUS, CUST_ID) 
    VALUES 
    ('HORIZON', '11-APR-2016', '10-APR-2021', 'OPEN', '10002');


--SELECT * FROM PROGRAMS;


--INSERT TEST DATA INTO 'PROGRAM_PART'

INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (101, 50001, 3);

INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (101, 50004, 1);
    
INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (103, 50004, 2);
    
INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (104, 50002, 2);
    
INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (101, 50003, 3);
    
INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (103, 50003, 1);
    
INSERT INTO PROGRAM_PART
    (PROG_ID, PART_ID, QTY_FACTOR)
    VALUES
    (102, 50004, 2);
    
--SELECT * FROM PROGRAM_PART;



--INSERT TEST DATA INTO 'OUTGOING_INVOICE'

INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('21-AUG-2017', 1400, 'NUMBER', 0.67, 'PER-PIECE', 60001); 
    
INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('03-SEP-2018', 850, 'NUMBER', 0.67, 'PER-PIECE', 60001); 

INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('18-FEB-2016', 690, 'POUNDS', 1.38, 'PER-LB', 60005);

INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('31-JAN-2017', 1950, 'NUMBER', 1.05, 'PER-PIECE', 60003);

INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('15-MAY-2019', 1000, 'NUMBER', 1.32, 'PER-PIECE', 60002);

INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('07-OCT-2018', 12000, 'NUMBER', 0.47, 'PER-PIECE', 60006);
    
INSERT INTO OUTGOING_INVOICE
    (OUT_INV_DATE, QUANTITY, QTY_UNIT, COST_PER_UNIT, COST_UNIT, PROG_PART_ID)
    VALUES
    ('30-NOV-2015', 1350, 'NUMBER', 1.30, 'PER-PIECE', 60007);
    
--SELECT * FROM OUTGOING_INVOICE;


--INSERT TEST DATA INTO 'EMPLOYEE_PROGRAM'

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123458, 102, 'PROGRAM MANAGER', '01-JUL-2017', NULL);

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123460, 104, 'SUPP_DEV_ENGINEER', '09-JAN-2012', '18-AUG-2014');

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123456, 101, 'PROGRAM MANAGER', '03-JAN-2014', '06-MAR-2016');

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123459, 101, 'PROGRAM MANAGER', '07-MAR-2016', '02-JAN-2019');
    
INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123457, 103, 'APQP REP', '13-MAY-2012', '26-FEB-2017');
    
INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123461, 104, 'PROGRAM MANAGER', '11-MAR-2011', '10-MAR-2016');

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123457, 103, 'PROGRAM MANAGER', '27-FEB-2012', '26-FEB-2017');

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE, END_DATE)
    VALUES
    (123460, 103, 'SUPP_DEV_ENGINEER', '11-MAY-2012', '02-FEB-2014');

INSERT INTO EMPLOYEE_PROGRAM
    (EMP_ID, PROG_ID, DESIGNATION, START_DATE)
    VALUES
    (123461, 105, 'PROGRAM MANAGER', '11-APR-2016');

--SELECT * FROM EMPLOYEE_PROGRAM;


--INSERT TEST DATA INTO 'APPROVAL_DETAILS'

INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50000, 303, 'APPROVED', '13-JAN-2019', 123460, 1.6);

INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50001, 305, 'APPROVED', '20-JUL-2015', 123459, 0.43);

INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50002, 302, 'APPROVED', '24-AUG-2013', 123458, 2.16);
    
INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50004, 302, 'PENDING', NULL, 123460, NULL);

INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50003, 301, 'APPROVED', '11-SEP-2015', 123457, 1.22);

INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50003, 301, 'DENIED', '09-NOV-2013', 123457, 1.10);

INSERT INTO APPROVAL_DETAILS
    (PART_ID, SUPP_ID, APP_STATUS, APP_DATE, SQE_REP, APP_COST)
    VALUES
    (50005, 304, 'PENDING', NULL, 123457, NULL);
  
--SELECT * FROM APPROVAL_DETAILS;


--INSERT TEST DATA INTO 'PURCHASE_ORDER'

INSERT INTO PURCHASE_ORDER
    (PART_APPR_ID, PO_DATE, ITEM_QTY)
    VALUES
    (4006, '06-MAR-2014', 3000);
    
INSERT INTO PURCHASE_ORDER
    (PART_APPR_ID, PO_DATE, ITEM_QTY)
    VALUES
    (4003, '12-DEC-2014', 850);
    
INSERT INTO PURCHASE_ORDER
    (PART_APPR_ID, PO_DATE, ITEM_QTY)
    VALUES
    (4002, '24-NOV-2017', 3300);
    
INSERT INTO PURCHASE_ORDER
    (PART_APPR_ID, PO_DATE, ITEM_QTY)
    VALUES
    (4005, '17-JAN-2017', 1350);
    
--SELECT * FROM PURCHASE_ORDER;
